fix: use `ruff check .` to actually lint

diff --git a/.github/workflows/reusable-python-code-quality.yaml b/.github/workflows/reusable-python-code-quality.yaml
--- a/.github/workflows/reusable-python-code-quality.yaml
+++ b/.github/workflows/reusable-python-code-quality.yaml
@@ -17,9 +17,8 @@ jobs:
           python -m pip install --upgrade pip
           python -m pip install ruff
 
-      - name: ruff format
-        if: ${{ !cancelled() }}
-        run: ruff format --diff || (echo 'Run `ruff format` to automatically re-format.' && exit 1)
+      - name: ruff check
+        run: ruff check --output-format=github || (echo 'Run `ruff check --fix` to automatically fix errors where possible.' && exit 1)
 
   formatting:
     runs-on: ubuntu-latest
